name: linter
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
on: [push]
jobs:
  checkout_code:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: checkout_node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm ci
  lint_and_format:
    needs: checkout_code
    steps: 
      - name: Run ESLint
        run: npm run lint

      - name: Run Prettier
        run: npm run format
  test: 
    needs: checkout_code
    steps:
      - run: echo "ğŸ This job's status is ${{ job.status }}."

