name: linter
run-name: ${{ github.actor }} is running GitHub Actions ğŸš€
on: [push]
jobs:
  checkout_code:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: checkout_node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Upload code as artifact
        uses: actions/upload-artifact@v4
        with:
          name: code
          path: ./meaning-future

  lint_and_format:
    runs-on: ubuntu-latest
    needs: checkout_code
    steps: 
      - name: download code artifact
        uses: actions/download-artifact@v4
        with:
          name: code
          path: ./meaning-future

      - name: install dependencies
        run: npm install
        working-directory: ./meaning-future

      - name: run ESLint 
        run: npm run lint

      - name: run Prettier
        run: npm run format

  test:
    runs-on: ubuntu-latest
    needs: checkout_code
    steps:
     - name: download code artifact
        uses: actions/download-artifact@v4
        with:
          name: code
          path: ./meaning-future

      - name: install dependencies
        run: npm install
        working-directory: ./meaning-future
        
      - run: echo "ğŸ This job's status is ${{ job.status }}."

